/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 desktop.gltf 
Author: Davide Specchi (https://sketchfab.com/Davide.Specchi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-desktop-09e39508a9a34d4e8f9ffbbf7189aaa4
Title: Apple Desktop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/desktop.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.01, 0.092, 1.457]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.48, 0.48, 0.426]}>
          <mesh geometry={nodes.Plane_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.000']} />
          <mesh geometry={nodes.Plane004_0.geometry} material={materials['Lamp.001']} />
          <mesh geometry={nodes.Plane003_0.geometry} material={materials['Lamp.001']} />
          <mesh geometry={nodes.Plane002_0.geometry} material={materials.Material} position={[-0.029, 2.229, -0.384]} rotation={[Math.PI / 2, 0, 0]} scale={[1.077, 0.117, 0.921]} />
          <mesh geometry={nodes.Plane001_0.geometry} material={materials.Material} position={[-0.029, 2.331, -0.384]} rotation={[Math.PI / 2, 0, 0]} scale={[1.077, 0.117, 0.921]} />
        </group>
        <mesh geometry={nodes.Cube_0.geometry} material={materials['Material.003']} position={[-0.01, 0.092, 1.457]} scale={0.426} />
        <mesh geometry={nodes.Plane005_0.geometry} material={materials['Material.001']} position={[-0.01, 0.103, 1.457]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.483, 0.471, 0.417]} />
        <mesh geometry={nodes.Keyboard_0.geometry} material={materials['Material.006']} position={[0, -1.309, 0.067]} rotation={[0.22, 0.018, 0.082]} scale={[1.098, 0.225, 0.006]} />
      </group>
    </group>
  )
}

useGLTF.preload('/desktop.gltf')
